const userTypes = {
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_CURRENT_USER_FROM_DB_START: "GET_CURRENT_USER_FROM_DB_START",
  GET_CURRENT_USER_FROM_DB_SUCCED: "GET_CURRENT_USER_FROM_DB_SUCCED",
  GET_CURRENT_USER_FROM_DB_FAILURE: "GET_CURRENT_USER_FROM_DB_FAILURE",
  LOGOUT_START: "LOGOUT_START",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export default userTypes;
