const userTypes = {
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_CURRENT_USER_FROM_DB_START: "GET_CURRENT_USER_FROM_DB_START",
  GET_CURRENT_USER_FROM_DB_SUCCED: "GET_CURRENT_USER_FROM_DB_SUCCED",
  GET_CURRENT_USER_FROM_DB_FAILURE: "GET_CURRENT_USER_FROM_DB_FAILURE",
};

export default userTypes;
